# Generated by Django 5.2.3 on 2025-07-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('occupation', models.CharField(choices=[('mechanic', 'Mechanic'), ('electrician', 'Electrician')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
